name: Deploy website

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Upgrade yarn.lock
        run: ./gradlew :kotlinUpgradeYarnLock

      - name: Execute Gradle build
        run: ./gradlew :jsBrowserDistribution

      - uses: actions/upload-pages-artifact@v2
        with:
          path: build/dist/js/productionExecutable

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v3
